// app/client/src/tombolaFrasi.js
export const tombolaFrasi = {
  1: { frase: "L'ITALIA", emoji: "🇮🇹" },
  2: { frase: "'A PICCERELLA", emoji: "👧" },
  3: { frase: "'A JATTA", emoji: "🐱" },
  4: { frase: "'O PUORCO", emoji: "🐷" },
  5: { frase: "'A MANO", emoji: "✋" },
  6: { frase: "QUELLA CHE GUARDA 'NTERRA", emoji: "👀" },
  7: { frase: "'A SCUFFIARA", emoji: "🧹" },
  8: { frase: "'A MARONNA", emoji: "🙏" },
  9: { frase: "'A FIGLIATA", emoji: "👨‍👩‍👧‍👦" },
  10: { frase: "'E FASULE", emoji: "🫘" },
  11: { frase: "'E SURICELLE", emoji: "🐭" },
  12: { frase: "'E SURDATE", emoji: "🎖️" },
  13: { frase: "SANT'ANTONIO", emoji: "⛪" },
  14: { frase: "'O MBRIACO", emoji: "🍺" },
  15: { frase: "'O GUAGLIONE", emoji: "👦" },
  16: { frase: "'O CULO", emoji: "🍑" },
  17: { frase: "'A DISGRAZIA", emoji: "⚠️" },
  18: { frase: "'O SANGHE", emoji: "🩸" },
  19: { frase: "'A RESATA", emoji: "😂" },
  20: { frase: "'A FESTA", emoji: "🎉" },
  21: { frase: "'A FEMMENA ANNURA", emoji: "👩" },
  22: { frase: "'O PAZZO", emoji: "🤪" },
  23: { frase: "'O SCEMO", emoji: "🤪" },
  24: { frase: "'E GUARDE", emoji: "👮" },
  25: { frase: "NATALE", emoji: "🎄" },
  26: { frase: "NANNINELLA", emoji: "👧" },
  27: { frase: "'O CANTERO", emoji: "🏺" },
  28: { frase: "'E ZIZZE", emoji: "💃" },
  29: { frase: "'O PATE 'E CCRIATURE", emoji: "👨‍👧‍👦" },
  30: { frase: "'E PPALLE D''O TENENTE", emoji: "⚽⚽" },
  31: { frase: "'O PADRONE 'E CASA", emoji: "👨‍💼" },
  32: { frase: "'O CAPITONE", emoji: "🐟" },
  33: { frase: "L'ANNE 'E CRISTO", emoji: "✝️" },
  34: { frase: "'A CAPA", emoji: "🧠" },
  35: { frase: "L'UCCIELLINO", emoji: "🐦" },
  36: { frase: "'E CASTAGNELLE", emoji: "🎵" },
  37: { frase: "'O MONACO", emoji: "🙏" },
  38: { frase: "'E MMAZZATE", emoji: "👊" },
  39: { frase: "'A FUNA 'NGANNA", emoji: "🪢" },
  40: { frase: "'A PAPOSCIA", emoji: "🤕" },
  41: { frase: "'O CURTIELLO", emoji: "🔪" },
  42: { frase: "'O CAFFÈ", emoji: "☕" },
  43: { frase: "'A FEMMENA 'O PUZZO", emoji: "👩⛲" },
  44: { frase: "'E CCANCELLE", emoji: "🔒" },
  45: { frase: "'O VINO", emoji: "🍷" },
  46: { frase: "'E DENARE", emoji: "💰" },
  47: { frase: "'O MUORTO", emoji: "💀" },
  48: { frase: "'O MUORTO CHE PARLA", emoji: "💀🗣️" },
  49: { frase: "'O PIEZZO 'E CARNE", emoji: "🍖" },
  50: { frase: "'O PPANE", emoji: "🍞" },
  51: { frase: "'O CIARDINO", emoji: "🌳" },
  52: { frase: "'A MAMMA", emoji: "👩" },
  53: { frase: "'O VIECCHIO", emoji: "👴" },
  54: { frase: "'O CAPPIELLO", emoji: "🎩" },
  55: { frase: "'A MUSECA", emoji: "🎵" },
  56: { frase: "'A CARUTA", emoji: "⬇️" },
  57: { frase: "'O SCARTELLATO", emoji: "🧍" },
  58: { frase: "'O PACCOTTO", emoji: "📦" },
  59: { frase: "'E PILE", emoji: "🐾" },
  60: { frase: "'O LAMENTO", emoji: "😭" },
  61: { frase: "'O CACCIATORE", emoji: "🎯" },
  62: { frase: "'O MUORTO ACCISO", emoji: "💀⚰️" },
  63: { frase: "'A SPOSA", emoji: "👰" },
  64: { frase: "'A SCIAMMERIA", emoji: "🎩" },
  65: { frase: "'O CHIANTO", emoji: "😢" },
  66: { frase: "'E DDOIE ZETELLE", emoji: "👭" },
  67: { frase: "'O TOTANO INT''A CHITARRA", emoji: "🐙🎸" },
  68: { frase: "'A ZUPPA COTTA", emoji: "🍲" },
  69: { frase: "SOTT'E 'NCOPPA", emoji: "⬇️⬆️" },
  70: { frase: "'O PALAZZO", emoji: "🏰" },
  71: { frase: "L'OMMO 'E MERDA", emoji: "💩" },
  72: { frase: "'A MERAVIGLIA", emoji: "✨" },
  73: { frase: "'O SPITALE", emoji: "🏥" },
  74: { frase: "'A ROTTA", emoji: "🕳️" },
  75: { frase: "PULLECENELLA", emoji: "🎭" },
  76: { frase: "'A FUNTANA", emoji: "⛲" },
  77: { frase: "'E RIAVULILLE", emoji: "😈" },
  78: { frase: "'A BELLA FIGLIOLA", emoji: "💃" },
  79: { frase: "'O MARIUOLO", emoji: "🦹" },
  80: { frase: "'A VOCCA", emoji: "👄" },
  81: { frase: "'E SCIURE", emoji: "🌺" },
  82: { frase: "'A TAVULA 'MBANDITA", emoji: "🍽️" },
  83: { frase: "'O MALETIEMPO", emoji: "⛈️" },
  84: { frase: "'A CCHIESA", emoji: "⛪" },
  85: { frase: "'E LL'ANEME 'O PRIATORIO", emoji: "👻" },
  86: { frase: "'A PUTECA", emoji: "🏪" },
  87: { frase: "'E PERUCCHIE", emoji: "🐛" },
  88: { frase: "'E CASECAVALLE", emoji: "🧀" },
  89: { frase: "'A VECCHIA", emoji: "👵" },
  90: { frase: "'A PAURA", emoji: "😱" }
};

export function getFraseForNumber(num) {
  return tombolaFrasi[num] || { 
    frase: `NUMERO ${num}`, 
    emoji: "🎲" 
  };
}